name: Entrenamiento de Modelos y Publicación de Artefactos

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    
    - name: Usar Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt 

    - name: Entrenar modelos BTC y SPY
      run: python proyecto_final_ia.py  

    - name: Publicar modelos como artefactos
      uses: actions/upload-artifact@v3
      with:
        name: models 
        path: output/  
