name: Entrenamiento de Modelos y Publicación de Artefactos

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    
    - name: Usar Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip 
        pip install yfinance pandas xgboost joblib scikit-learn 
    - name: Verificar el directorio actual
      run: |
        pwd   # Imprime el directorio actual
        ls -al  # Lista los archivos en ese directorio

    
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Entrenar modelos BTC y SPY
      run: python scr/proyecto_final_ia.py  
      working-directory: ${{ github.workspace }}
      
    - name: Publicar modelos como artefactos
      uses: actions/upload-artifact@v3
      with:
        name: models 
        path: output/  
